language: scala
scala:
  - 2.10.0
script:
  - "sbt -Duser.name=$USER.$RANDOM ++$TRAVIS_SCALA_VERSION assembly"
  - "scripts/test_tutorials.sh"
jdk:
  #the scala compiler has problems with jdk7 intermittenly
  - openjdk6
